metadata:
  name: common-tasks
  description: 
  labels:
    platform: ep
    jira-project: EP
    jira-board: 159
    public: false
    sensitive: false
  links:
    - title: Engineering Platform
      url: https://adgear.atlassian.net/wiki/spaces/ENG/pages/19053052021/EP+Engineering+Platform
spec:
  owner: cg-ep
  type: infrastructure
  lifecycle: production